### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by phazei** [aemkei/jsfuck#40]
If the file is too big it is too large for the string.

```js
λ ..\node_modules\.bin\jsfuck crawler.js
C:\test\node_modules\jsfuck\jsfuck.js:235
output = output.join("+");
^
RangeError: Invalid string length
at Array.join (native)
at Object.encode (C:\test\node_modules\jsfuck\jsfuck.js:235:21)
at Object.<anonymous> (C:\test\node_modules\jsfuck\fuck.js:11:25)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:501:10)
at startup (node.js:129:16)
   at node.js:814:3
```

Perhaps it could stream it to the file line by line rather than putting it into a single string first?

**Comment by aemkei** [comment]
Streaming would be a good solution! But that will require some bigger refactoring.
